### ISSUE TITLE
Port mapping not working

### ISSUE THREAD

**Issue by poperigby** [Maroka-chan/VPN-Confinement#10]
I'm trying to map qBittorrent's Web UI port from inside to outside of the network namespace.

Here's my config:

```nix
{ config, inputs, pkgs, ... }:

let
    cfg = config.services.qbittorrent;
in
{
    imports = [
        "${inputs.qbittorrent}/nixos/modules/services/torrent/qbittorrent.nix"
        inputs.vpnconfinement.nixosModules.default
    ];

    services = {
        qbittorrent = {
            enable = true;
            webuiPort = 8083;
            torrentingPort = 4096;
        };
        caddy.virtualHosts."torrent.haddock.cc".extraConfig = ''
            import auth
            reverse_proxy :${builtins.toString cfg.webuiPort}
        '';
    };

    # Define a network namespace with a VPN for qBittorrent
    vpnnamespaces.proton0 = {
        enable = true;
        wireguardConfigFile = config.sops.templates.wireguard-config-file.path;
        accessibleFrom = [
            "192.168.0.0/24"
        ];
        portMappings = [
            {
                # Make the WebUI accessible outside the namespace
                from = cfg.webuiPort;
                to = cfg.webuiPort;
            }
        ];
    };

    systemd.services = {
        qbittorrent = {
            # Make qBittorrent run in the ProtonVPN network namespace
            vpnconfinement = {
                enable = true;
                vpnnamespace = "proton0";
            };
        };
    };

    sops = {
        templates.wireguard-config-file = {
            content = # toml
            ''
                [Interface]
                # Key for Haddock
                # Bouncing = 20
                # NetShield = 1
                # Moderate NAT = off
                # NAT-PMP (Port Forwarding) = on
                # VPN Accelerator = on
                PrivateKey = ${config.sops.placeholder."haddock/protonvpn/private_key"}
                Address = 10.2.0.2/32
                DNS = 10.2.0.1

                [Peer]
                # US-WA#103
                PublicKey = mdgZ6wT7AXGznoYqxERZexx9aPEd/FhQ+P6fdXCBuVQ=
                AllowedIPs = 0.0.0.0/0
                Endpoint = 149.102.254.78:51820
            '';
            owner = "qbittorrent";
        };
        secrets = {
            "haddock/protonvpn/private_key".owner = "qbittorrent";
        };
    };
}
```

When I run `sudo netstat -tulpn` outside the namespace, qBittorrent doesn't show up in the list, but it does when I run it with `sudo ip netns exec proton0 netstat -tulpn`.

**Comment by Maroka-chan** [comment]
QBittorrent not showing up with netstat outside the netns is expected.
It seems like you have not told qbit to listen on the bridge address, so that's most likely your problem.
If you haven't already, you should check that accessibleFrom is set correctly -> `ip r`
Also, if you want to use the torrent port through the VPN, you should specify it in  the `openVPNPorts` option. I admit it's a bad name given it has nothing to do with OpenVPN.
oh also, you don't need to use caddy to access the service if that's what it is for.

**Comment by Maroka-chan** [comment]
> This is its output, which doesn't seem right?

With a mask of 24 your machines are on a different subnet from the example :)
Keeping the same mask you can just change it to
```
accessibleFrom = [ "192.168.1.0/24" ];
```
You could also change the mask to /16 if you require that.
192.168.1.0/24 allows 192.168.1.\*
192.168.0.0/16 allows 192.168.\*.\*
Hope that makes sense.
> Do you mean the port used for torrenting? I think it should be okay not to expose it, right?

Oh yeah it's not at all necessary, I just assumed you wanted to be an active seeder since you had specified a port. Maybe it has another purpose and I'm just misunderstanding ^^'
> Perhaps it should be renamed to exposeVPNPorts?

Yeah that sounds better, something along those lines :)

**Comment by poperigby** [comment]
> With a mask of 24 your machines are on a different subnet from the example :)
> Keeping the same mask you can just change it to
> 
> ```accessibleFrom = [ "192.168.1.0/24" ];```
> 
> You could also change the mask to /16 if you require that.
> 192.168.1.0/24 allows 192.168.1.*
> 192.168.0.0/16 allows 192.168.*.*
> Hope that makes sense.

Dang, it still doesn't work. I have qBittorrent listening on all interfaces. Sorry, I'm really bad with network masks.

> Oh yeah it's not at all necessary, I just assumed you wanted to be an active seeder since you had specified a port. Maybe it has another purpose and I'm just misunderstanding ^^'

Oh I see what you mean, that option exposes the ports through the firewall? That's actually a bit of a problem, because I ProtonVPN gives me a different port every restart, and I update it with this [script](https://codeberg.org/PopeRigby/nixos/src/commit/1d11841d553c45c17d4f9e241a2892c66cce4679/packages/qbittorrent-protonvpn-port-update/default.nix). Maybe I could expose the port in my script?

**Comment by Maroka-chan** [comment]
> Dang, it still doesn't work. I have qBittorrent listening on all interfaces. Sorry, I'm really bad with network masks.

Can you explain how you're trying to access it, like whether it's from another machine and which address you are using? 
It would also help to see your updated config :)

> Oh I see what you mean, that option exposes the ports through the firewall? That's actually a bit of a problem, because I ProtonVPN gives me a different port every restart, and I update it with this [script](https://codeberg.org/PopeRigby/nixos/src/commit/1d11841d553c45c17d4f9e241a2892c66cce4679/packages/qbittorrent-protonvpn-port-update/default.nix). Maybe I could expose the port in my script?

You could do it in your script, but it becomes a bit hacky. You need it to run after the netns has been set up, and if the setup service is restarted, you lose the change. You would do it like this if you want to try.
`ip netns exec proton0 iptables -A INPUT -p <protocol> --dport <port> -j ACCEPT -i proton00`

If you just needed the port to change on a rebuild, you could fetch it at evaluation time, but it truly becomes quite tricky if you want it on boot with a pure config.
Handling dynamic ports seems like a nightmare. I'm impressed you made it work instead of just changing provider haha.
What I *could* do is make an option to disable the firewall inside the netns if you would prefer that?

**Comment by poperigby** [comment]
> Can you explain how you're trying to access it, like whether it's from another machine and which address you are using?

I have it reverse proxied with Caddy, so I'm accessing it at https://torrent.haddock.cc

> It would also help to see your updated config :)

Sure. Here's my updated config:

```nix
# Setup based on https://trash-guides.info/Hardlinks/How-to-setup-for/Native/#torrent-clients

{ config, inputs, pkgs, ... }:

let
    cfg = config.services.qbittorrent;
in
{
    imports = [
        "${inputs.qbittorrent}/nixos/modules/services/torrent/qbittorrent.nix"
        inputs.vpnconfinement.nixosModules.default
    ];

    services = {
        qbittorrent = {
            enable = true;
            webuiPort = 8083;
            torrentingPort = 4096;
            serverConfig = {
                Application.FileLogger = {
                    Age = 1;
                    AgeType = 1;
                    Backup = true;
                    DeleteOld = true;
                    Enabled = true;
                    MaxSizeBytes = 66560;
                    Path = "/var/log/qBittorrent";
                };
                BitTorrent.Session = {
                    AlternativeGlobalDLSpeedLimit = 0;
                    AlternativeGlobalUPSpeedLimit = 0;
                    BTProtocol = "TCP";
                    BandwidthSchedulerEnabled = true;
                    DefaultSavePath = "/mnt/media/data/torrents";
                    DisableAutoTMMByDefault = false;
                    # DisableAutoTMMTriggers = {
                    #     CategorySavePathChanged = false;
                    #     DefaultSavePathChanged = false;
                    # };
                    ExcludedFileNames = "";
                    GlobalDLSpeedLimit = 1736704;
                    GlobalUPSpeedLimit = 1736704;
                    Preallocation = true;
                    QueueingSystemEnabled = false;
                    TempPath = "/tmp/qBittorrent";
                    UseAlternativeGlobalSpeedLimit = true;
                    # Bind to the ProtonVPN WireGuard interface to avoid leaks
                    # Interface = "proton0";
                    # InterfaceName = "proton0";
                };
                Core.AutoDeleteAddedTorrentFile = "IfAdded";
                LegalNotice.Accepted = true;
                Meta.MigrationVersion = 6;
                Network.PortForwardingEnabled = false;
                Preferences = {
                    General.Locale = "en";
                    Scheduler = {
                        end_time = "@Variant(\0\0\0\xf\x1I\x97\0)";
                        start_time = "@Variant(\0\0\0\xf\x4\xefm\x80)";
                    };
                    WebUI = {
                        # I have Authelia in front of qBittorrent, so WebUI login is unnecessary
                        AuthSubnetWhitelist = "0.0.0.0/0";
                        AuthSubnetWhitelistEnabled = true;
                        HostHeaderValidation = false;
                        CSRFProtection = false;
                    };
                };
            };
        };
        caddy.virtualHosts."torrent.haddock.cc".extraConfig = ''
            import auth
            reverse_proxy :${builtins.toString cfg.webuiPort}
        '';
    };

    # Give qBittorrent access to /mnt/media/data/torrents
    users.users.qbittorrent.extraGroups = [ "torrents" ];

    # Define a network namespace with a VPN for qBittorrent
    vpnnamespaces.proton0 = {
        enable = true;
        wireguardConfigFile = config.sops.templates.wireguard-config-file.path;
        accessibleFrom = [
            "192.168.1.0/24"
        ];
        portMappings = [
            {
                # Make the WebUI accessible outside the namespace
                from = cfg.webuiPort;
                to = cfg.webuiPort;
            }
        ];
    };

    systemd.services = {
        qbittorrent = {
            # Make qBittorrent run in the ProtonVPN network namespace
            vpnconfinement = {
                enable = true;
                vpnnamespace = "proton0";
            };
        };
        # Automatically update the qBittorrent torrenting port with the one forwarded in ProtonVPN
        qbittorrent-protonvpn-port-update = {
            enable = true;
            description = "Automatically update the qBittorrent torrenting port with the one forwarded in ProtonVPN";
            wants = [ "qbittorrent.service" ];
            wantedBy = [ "multi-user.target" ];
            after = [ "qbittorrent.service" ];
            environment = {
                QBITTORRENT_WEBUI_HOST = "127.0.0.1";
                QBITTORRENT_WEBUI_PORT = builtins.toString cfg.webuiPort;
                QBITTORRENT_WEBUI_USERNAME = "admin";
                QBITTORRENT_WEBUI_PASSWORD = "adminadmin";
                INITIAL_DELAY_SEC = "10";
                CHECK_INTERVAL_SEC = "60";
                ERROR_INTERVAL_SEC = "5";
                ERROR_INTERVAL_COUNT = "5";
            };
            serviceConfig = {
                Type = "simple";
                ExecStart = "${pkgs.poperigby.qbittorrent-protonvpn-port-update}/bin/qbittorrent-protonvpn-port-update";
            };
            # Make the port updater run in the ProtonVPN network namespace
            vpnconfinement = {
                enable = true;
                vpnnamespace = "proton0";
            };
        };
    };

    sops = {
        templates.wireguard-config-file = {
            content = ''
                [Interface]
                # Key for Haddock
                # Bouncing = 20
                # NetShield = 1
                # Moderate NAT = off
                # NAT-PMP (Port Forwarding) = on
                # VPN Accelerator = on
                PrivateKey = ${config.sops.placeholder."haddock/protonvpn/private_key"}
                Address = 10.2.0.2/32
                DNS = 10.2.0.1

                [Peer]
                # US-WA#103
                PublicKey = mdgZ6wT7AXGznoYqxERZexx9aPEd/FhQ+P6fdXCBuVQ=
                AllowedIPs = 0.0.0.0/0
                Endpoint = 149.102.254.78:51820
            '';
            owner = "qbittorrent";
        };
        secrets = {
            "haddock/protonvpn/private_key".owner = "qbittorrent";
        };
    };
}
```

> You could do it in your script, but it becomes a bit hacky. You need it to run after the netns has been set up, and if the setup service is restarted, you lose the change. You would do it like this if you want to try.
>```ip netns exec proton0 iptables -A INPUT -p <protocol> --dport <port> -j ACCEPT -i proton00```

The only time when the port changes is when the WireGuard connection restarts, and I could just make the script only start after the service that creates the netns starts. Why would it be hacky though?

>  Handling dynamic ports seems like a nightmare. I'm impressed you made it work instead of just changing provider haha.

I don't think there are any other providers that actually respect privacy and support port forwarding :cry: 

>  What I could do is make an option to disable the firewall inside the netns if you would prefer that?

That would certainly be helpful, but I'm a bit worried about the security of it.
That would certainly be helpful

**Comment by Maroka-chan** [comment]
> I have it reverse proxied with Caddy, so I'm accessing it at https://torrent.haddock.cc/

Try accessing it on your LAN from another machine or directly on the host with the bridge address. It would be nice to rule out whether the reverse proxy causes any problems :x

You will also need to use the bridge address when you want to access it on the host, so you should change `QBITTORRENT_WEBUI_HOST`. The default bridge address is 192.168.15.1

> The only time when the port changes is when the WireGuard connection restarts, and I could just make the script only start after the service that creates the netns starts. Why would it be hacky though?

It's probably not so bad if you set `bindsTo = [ "proton0.service" ];` and `after = [ "proton0.service" ];`.
It does mean that the options for vpnnamespaces are no longer the single source of truth, but I think that's difficult to get around unless you go with just disabling the firewall.
I hope you get it working :) Let me know if you need help or if you do want me to make that option.

**Comment by poperigby** [comment]
> Try accessing it on your LAN from another machine or directly on the host with the bridge address. It would be nice to rule out whether the reverse proxy causes any problems :x

Ah, figured it out. I had to reverse proxy `192.168.15.1:8083`, not `localhost:8083`.

> You will also need to use the bridge address when you want to access it on the host, so you should change QBITTORRENT_WEBUI_HOST. The default bridge address is 192.168.15.1

Because the script is running inside the netns, localhost actually works fine. Thanks for telling me though :slightly_smiling_face: 

> It's probably not so bad if you set bindsTo = [ "proton0.service" ]; and after = [ "proton0.service" ];.
> It does mean that the options for vpnnamespaces are no longer the single source of truth, but I think that's difficult to get around unless you go with just disabling the firewall.

Yeah, I'm fine with that.

>  I hope you get it working :) Let me know if you need help or if you do want me to make that option.

Thanks for all your help!

**Comment by Maroka-chan** [comment]
> Because the script is running inside the netns, localhost actually works fine. Thanks for telling me though 🙂

Ah yes that makes sense, I missed that it was also running in the netns ^^'
I'm glad you figured it out :)

**Comment by poperigby** [comment]
Thanks! If I open the torrenting port inside the netns, that should be good enough, right? I don't have to open it anywhere else?

**Comment by Maroka-chan** [comment]
Yep, that should suffice :)
Also to clarify just in case, you don't need to open ports on the hosts default network for services that run in the VPN netns. This is because packets for ports defined in `portMappings` are prerouted to the netns before they can hit the input chain, so they hit the input chain defined in the netns instead, and `portMappings` adds input rules so you shouldn't need to do anything extra :)

**Comment by ImUrX** [comment]
I come to share my cursed module in here, it's submodule based so you can use as many VPN confinements for port forwarding via ProtonVPN:
https://github.com/ImUrX/nixfiles/blob/b07d94b2a7dec5c5d8c93d60b706434db3514554/modules/wg-pnp.nix

**Comment by 74k1** [comment]
I should share mine too then: https://github.com/reo101/ouro :)
Written in Rust, & it's a little more service specific. (Transmission & Slskd for now)

**Comment by ImUrX** [comment]
😆, good to know im not the only one doing this
