### ISSUE TITLE
"The option vpnnamespaces is used but not defined"

### ISSUE THREAD

**Issue by rasmus-kirk** [Maroka-chan/VPN-Confinement#12]
The following error appears if the module is imported with no vpnnamespaces defined.

**Comment by poperigby** [comment]
That just means that `vpnnamespaces` is a required option, meaning you have to set it.

**Comment by rasmus-kirk** [comment]
In my opinion, importing a flake should not require you to set any options. If you do set options from an imported flake, I would however find it reasonable that they require other options to be set.

**Comment by Maroka-chan** [comment]
Should be fixed by e8ea92903b36d096c01f977393fbe79f8ed25b42
