### ISSUE TITLE
IPv6 support?

### ISSUE THREAD

**Issue by misuzu** [Maroka-chan/VPN-Confinement#16]
Adding a (globally routable) IPv6 address to the `Address` option just assigns the address to the wg interface and does not configure default route or firewall.
Running `sudo ip netns exec wg-namespace ip -6 route add default dev wg-interface` makes `sudo ip netns exec wg-namespace ping -6 google.com` work, but manually running this is not great. It also needs to be hardened by firewall rules (allowing only `openVPNPorts`)

**Comment by Maroka-chan** [comment]
It took a lot of time, but I learned a bunch about IPv6 along the way :+1: 
There's two new ipv6 specific options, `namespaceAddressIPv6` and `bridgeAddressIPv6`. I might merge them with the ipv4 options at some point.
You shouldn't need to change the defaults, but you might want to add an ipv6 address to `accessibleFrom`.

Try out the [feat/ipv6-support](/Maroka-chan/VPN-Confinement/tree/feat\/ipv6-support) branch and see if it works for you :)

**Comment by misuzu** [comment]
> Try out the [feat/ipv6-support](/Maroka-chan/VPN-Confinement/tree/feat/ipv6-support) branch and see if it works for you :)

It works perfectly, thank you!
