### ISSUE TITLE
Fails to bring up network interface if networking.enableIPv6 is false

### ISSUE THREAD

**Issue by lunik1** [Maroka-chan/VPN-Confinement#19]
After the merge of #17 the systemd service for my network has started failing. I have tracked it down to this line in the `-up` script:
```
++ ip addr add fd93:9701:1d00::1/64 dev vpnnet-br
Error: ipv6: IPv6 is disabled on this device.
```

This seems to be because ipv6 is disabled on the machine, with `networking.enableIPv6 = false`.

**Comment by Maroka-chan** [comment]
Thanks for reporting this.
I've now made it so that ipv6 commands are only added if `networking.enableIPv6` is true -> c7415e6
Let me know if this solves the issue :)

**Comment by lunik1** [comment]
Yes, thanks for the quick fix!
