### ISSUE TITLE
Bug: Namespace name does not allow `-`

### ISSUE THREAD

**Issue by rasmus-kirk** [Maroka-chan/VPN-Confinement#2]
It seems like the module maps `-` to `/` which leads to invalid names. If I add a namespace name like:

```nix
    vpnnamespaces.testing-vpn = {
      enable = cfg.vpn.enable ;
      accessibleFrom = [
        "192.168.1.1/24"
        "127.0.0.1"
      ];
      wireguardConfigFile = cfg.vpn.wgConf;
    };
```

Then I will get an error:

```
Invalid netns name "testing/vpn"
```

**Workaround:** Use camelCase :shrug:

**Comment by Maroka-chan** [comment]
Cannot reproduce.
It might have been fixed since. This would still fail though as the [name is too long](https://github.com/Maroka-chan/VPN-Confinement/issues/3#issuecomment-2153560700).
