### ISSUE TITLE
Doesn't seem like it can handle longer namespace names

### ISSUE THREAD

**Issue by rasmus-kirk** [Maroka-chan/VPN-Confinement#3]
I couldn't build with namespace name `nixarrVpn`, worked with `wg`

**Comment by Maroka-chan** [comment]
The name of network interfaces are limited to 15 characters. One of the interfaces the module creates is named `veth-${name}-br`, which limits the name to 7 characters. I could shorten the name if needed, but for now I have just made an assertion to make it fail if the name exceeds this limit.
