### ISSUE TITLE
Make options camelCase?

### ISSUE THREAD

**Issue by poperigby** [Maroka-chan/VPN-Confinement#9]
This is a silly little nitpick, but maybe the options should be camelCase to match NixPkgs.`vpnConfinement` instead of `vpnconfinement`, `vpnNamespace` instead of `vpnnamespace`, etc.

**Comment by Maroka-chan** [comment]
Not silly at all :) They should of course be consistent with the other options.
They have been renamed in 07b56008396368cb5f6298d5c0a31141d0b3741b

A warning is only thrown for `vpnnamespaces`, but the other options have been renamed as well.
`mkRenamedOptionModule` does not throw warnings when defined in a submodule for some reason. It might be related to this [issue](https://github.com/NixOS/nixpkgs/issues/96006).

**Comment by poperigby** [comment]
Thanks :slightly_smiling_face:
